### ISSUE TITLE
Enabling "Show popup messages when changing tracks" results in notification displayed until next track starts

### ISSUE THREAD

**Issue by xfzv** [nullobsi/cantata#17]
On Gentoo (X11) with AwesomeWM, Cantata compiled from source with:

https://github.com/nullobsi/cantata/blob/cf195772188772363b5326c9f227d9efb41fe438/INSTALL#L4-L6

If enabling `Settings > Interface > External > Show popup messages when changing tracks`, notifications are displayed when changing track, but they're still visible until the next track kicks in, and so on. Even if I pause or stop playback, a notification with the currently paused or last played track will be visible forever unless I manually dismiss it with a mouse click.

I never had this issue with original version from CDrummond, which I've used for years.

Here's my notifications config for AwesomeWM if that matters:

```lua
local naughty = require("naughty")
local rnotification = require("ruled.notification")

rnotification.connect_signal("request::rules", function()
  rnotification.append_rule({
    rule = { urgency = "critical" },
    properties = {
      bg = "#1E1E20",
      border_color = "#EBA0AC",
      border_width = 2,
      fg = "#CDD6F4",
      icon_size = 48,
      implicit_timeout = 0,
      position = "top_right",
    },
  })

  rnotification.append_rule({
    rule = { urgency = "normal" },
    properties = {
      bg = "#1E1E20",
      border_color = "#505052",
      border_width = 2,
      fg = "#CDD6F4",
      icon_size = 48,
      implicit_timeout = 10,
      position = "top_right",
    },
  })

  rnotification.append_rule({
    rule = { urgency = "low" },
    properties = {
      bg = "#1E1E20",
      border_color = "#505052",
      border_width = 2,
      fg = "#CDD6F4",
      icon_size = 48,
      implicit_timeout = 10,
      position = "top_right",
    },
  })
end)

naughty.connect_signal("request::display", function(n)
  naughty.layout.box({ notification = n })
end)

-- Error handling
naughty.connect_signal("request::display_error", function(message, startup)
  naughty.notification({
    urgency = "critical",
    title = "Oops, an error happened" .. (startup and " during startup!" or "!"),
    message = message,
  })
end)
```

Running

```console
% notify-send "Test"
```

displays a notification for 10 seconds as expected (`implicit_timeout = 10,`).

I don't think Cantata notifications are interpreted as "critical" notifications by AwesomeWM since they're using `#505052` for borders (used for "normal" and "low" urgency notifications), not `#EBA0AC` (for "critical" notifications).

**Comment by nullobsi** [comment]
this is probably a result of the work I did in fff07407f701f65e5efd2789a67c9bd50ad6aa51.

the notification is specified as a low urgency notification that is persistent, because it is updated and not removed. therefore, it is never dismissed automatically, but goes away when the next song is updated.

https://github.com/nullobsi/cantata/blob/cf195772188772363b5326c9f227d9efb41fe438/gui/trayitem.cpp#L204

i'll make it no longer persistent (i think I misunderstood what it meant semantically)

when I do, could you please test it on your setup?
