### ISSUE TITLE
Crash when changing track

### ISSUE THREAD

**Issue by xfzv** [nullobsi/cantata#22]
**System Details**
- OS: Gentoo
- Arch : amd64
- Desktop Environment: AwesomeWM
- Version : 3.2.0 (https://github.com/nullobsi/cantata/commit/0d463d7c7ad55e1f06159eea0ce3b6482bd52a5f)
- Installed by: Compiled

**Describe the bug**

When changing track, sometimes Cantata crashes. It happens randomly but I could trigger the crash 4 times in a couple of minutes:

```console
Unfortunately Cantata has crashed. Please report a bug at
https://github.com/nullobsi/cantata/issues/ and include the following stack trace:

  /usr/lib64/libc.so.6 : ()+0x3c390
  ./cantata : ()+0x4c4bf6
  ./cantata : ()+0x1a403e
  ./cantata : ()+0x13e116
  ./cantata : ()+0x153e28
  /usr/lib64/libQt6Core.so.6 : QObject::event(QEvent*)+0x23b
  /usr/lib64/libQt6Widgets.so.6 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x85
  /usr/lib64/libQt6Core.so.6 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x160
  /usr/lib64/libQt6Core.so.6 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x236
  /usr/lib64/libQt6Core.so.6 : ()+0xc3087
  /usr/lib64/libglib-2.0.so.0 : ()+0x575f4
  /usr/lib64/libglib-2.0.so.0 : ()+0x5a747
  /usr/lib64/libglib-2.0.so.0 : g_main_context_iteration()+0x30
  /usr/lib64/libQt6Core.so.6 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x70
  /usr/lib64/libQt6Core.so.6 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x14a
```

**To Reproduce**

1. Open Cantata
2. Change track with mouse or with keyboard shortcut
3. Sometimes, Cantata crashes

**Expected behavior**

No crash

**Additional context**

Not sure if this matters but changing track is a bit laggy on my system. Double clicking on a track or using Previous/Next track shortcuts takes about 2 seconds before the new track starts playing. No issue with CDrummond version, it's instant.

The rest of the UI is very responsive (menus, seeking, re-ordering playlist, removing tracks from the playlist...).

**Comment by nullobsi** [comment]
I'm pretty sure this is an issue with the song notifications. I'll see how to make the dispatch happen on a background thread to make the UI snappier.

To confirm, I turned on/off the "Pop-up notifications" setting. With it on, there is that ~2s delay in the UI update. With it off, I see no such delay.

As for the crash, unfortunately the back-trace is missing debug symbols. My guess is a bad dereference, but if possible, try compiling Cantata with the `Debug` or `RelWithDebInfo` CMake build type.

**Comment by nullobsi** [comment]
I have fixed (more of a mitigation) the GUI responsiveness issue, and I believe I've addressed the crash in the linked PR. It just needs some testing on other platforms that aren't Linux.
