### ISSUE TITLE
settings/playlists are lost when upgrading from 2.5.0

### ISSUE THREAD

**Issue by zdykstra** [nullobsi/cantata#30]
**System Details**
OS: Void Linux
Arch: x86_64-glibc
Desktop Environment: KDE
Version: v3.2.0
Installed by: System, from a proposed package update

**Describe the bug**

I'm not sure if this is considered a bug, or intentional behavior. When upgrading from Cantata 2.5.0, the last official release prior to the original author archiving the project/repo, I receive a "First Run" dialog. Cantata 2.5.0 uses `cantata` as a directory name for configuration files, where this project uses `Cantata`. 

Updating Cantata on all Void systems to this maintained fork will result in everybody having to reconfigure their application from scratch. Is there a full, or even partial, migration path from 2.5.0 to 3.2.0 that doesn't involve recreating everything? I copied everything from `.local/share/cantata` to `.local/share/Cantata` without any obvious bad behavior after that. 

**To Reproduce**
1. Upgrade from the last upstream release of Cantata 2.5.0 to 3.2.0 from this repository
2. Reconfigure Cantata from scrach.

**Expected behavior**
All previous settings, playlists, etc are still available.

**Additional context**
It looks like https://github.com/nullobsi/cantata/commit/1e4bbad2650b59f420eb53faf823e76cad61d5b2 is what potentially introduced this change.

**Comment by nullobsi** [comment]
I can add a check to let users migrate data from the older versions.

**Comment by nullobsi** [comment]
Should be fixed in the latest commit
