### ISSUE TITLE
Not all cover art showing in grid display

### ISSUE THREAD

**Issue by alan12345678** [nullobsi/cantata#36]
Only recently discovered your lovely branch of my all-time favourite player - so thank you for this!!

Having run the original cantata for years now, I naturally had most things already set. So, once I replaced it with your version, I already had the full cache of all the album art copied over from the now superseded version.

I always (and pretty much only) ever use the grid view, grouped by album. So I'm used to seeing the full display of all covers. I disable the option to download them because _every single_ track in my library is correctly tagged and has embedded art.

Now though, I see there are blank spaces where the album art should be. It's only a small number, but despite several logging out and back in, various tries at refreshing or re-creating the album art caches, there are still blanks.

Do I need to simply wait a bit longer while it "catches up"?

FYI and in case it might be related: the albums missing the art are all a bit "irregular" insofar as the album titles may contain a colon - as in "Nigeria 70: The Definitive Story Of..." - or "S.C.I.E.N.C.E." by Incubus. I use a local mpd instance, and my library is on an ext4 partition, so I allow "illegal" Windows/MS file names to include question marks, colons etc.

**Comment by nullobsi** [comment]
The cache directory is by default under ~/.cache/cantata/covers . (If you're using flatpak, this will be different.) There, they're all labelled simply like $artist_name/$album_name. Check to see if the cache contains entries for the album. 

Note to self: I should probably change that logic to use hashes for the cache, to prevent issues with funky file naming on other OSes.

**Comment by alan12345678** [comment]
Because I copied over the cache from cantata (yours installs as Cantata), that cache location also held a directory labelled "covers-scaled" and I have copied this too. So the answer to whether there's a named folder for a problematic cover image is "it depends".

For the missing art there's nothing in ~/.cache/Cantata/covers.

In the original cantata there was a config option to set the size of the cover tiles in the grid. I note that this option doesn't seem to exist in your version, but inside ~/.cache/cantata/covers-scaled were dirs for different sizes e.g. 32, 40, 45, 128, 136 so I copied these directories too although they may now be irrelevant. However, due to my previous experiments with the grid sizing and the subsequent expansion of my music library, they contain partial subsets of the contents of ~/.cache/Cantata/covers and thus some of them do contain an entry that's not in ~/.cache/Cantata/covers but for the most part no.

One difference to note perhaps: if I want to change the album art for an existing (not missing) entry, the "right click > set image" leads to a search pane where the existing image is listed as "current cover" with some size information.

When I attempt to set an image for a missing cover, that dialogue window doesn't exist i.e. it's not there but blank, it isn't there at all.

Even using those search results wouldn't be so bad (in fact sites like Deezer and iTunes mostly make a really good job of the cover art) but not only do I have just shy of 7000 covers, but in some cases there is no online art to be found, due to the tune itself being quite rare? So I much prefer that all the embedded art gets displayed if possible.

**Comment by alan12345678** [comment]
can add the following:

having just added three new albums to my library, I opened Cantata - which has picked up the albums - but NO art at all.

Note that I have disabled any automatic downloading of images, as not only are all my music have embedded art, but quite often the cover chosen will be undesired e.g. if it's for a remix or reissue. I like to stick to "original" cover art. So, methinks this isn't picking up embedded art at all? It's only showing what it does because I imported the cache from my previous install?

**Comment by nullobsi** [comment]
a few other questions, just to cover some bases

what version of MPD are you using, and from what distribution?

could you send me one of the song files with embedded album art that is not showing in cantata, so i can reproduce?

**Comment by alan12345678** [comment]
mpd 0.23.15  on Arch Linux. I run a local user instance of mpd via a systemd unit.

I will find and attach a file for you later, but in the meantime please note my last post above in which I stated that after adding new albums to my library and starting Cantata-qt6, NO art was applied at all.

This leads me to believe that on my distro, album art has only shown up at all because it was in the copied cache file from my original cantata (the now archived version). Were I to in fact delete album art cache entirely and restart Cantata-qt6, I suspect it would show no art at all.

I would test this except that I have since reverted to my original version. Not helpful I know, but it works faultessly.

**Comment by outfoxxed** [comment]
I've recently switched to this fork and can confirm that embedded art is broken while `cover.<type>` images in the folder work as expected. As far as I can see, every instance of embedded cover art is broken for me.

**Comment by nullobsi** [comment]
that would make sense considering I almost exclusively use cover image files in my folders, and I haven't ran into this issue. i peeked at the image cover code a while ago and it seems pretty complex for what should be a fairly simple caching task; perhaps it needs to be refactored.

**Comment by outfoxxed** [comment]
It works in the original cantata, so looking through the old and current implementation should be helpful.

**Comment by nullobsi** [comment]
Cantata never had any code that used `readpicture`, which is what reads embedded cover art. There is also code in cantata-tags to read embedded art from files, but this requires TagLib which is not included in the Flatpak version and in a some packaged versions (since TagLibv2 is packaged weirdly.) Anyway, using `readpicture` is probably better because it will work for remote MPD servers too. Check the linked PR.
