### ISSUE TITLE
bug: No timestamp for podcast episodes

### ISSUE THREAD

**Issue by Nohoy** [nullobsi/cantata#37]
**System Details**
OS: [OpenSUSE Tumbleweed]
Arch: [x64]
Desktop Environment: [KDE]
Version: v3.2.1
Installed by: [Zypper]

**Describe the bug**
Podcasts episodes don't display timestamp anymore. When importing podcasts from previous Cantata install, timestamp is shown, but then new podcast episodes do not show up when refreshing.

**To Reproduce**
1. Go to 'Internet'
2. Click on 'Podcasts'
3. Add podcast using 'Add' button
4. Refresh list
5. See all podcasts being arranged alphabetically instead of by date

**Expected behavior**
Refreshing will add new podcast episodes to top of the list.

**Screenshots**
![Schermafdruk_20241102_201945](https://github.com/user-attachments/assets/1da2e5f4-c08a-4fab-8a9c-6d59f97825f9)

**Additional context**
After having set up Cantata following Tumbleweed's update from 2.5.0 and finding all of my timestamp data missing, I copy-pasted the old "cantata" user folder into the new "Cantata" one. This time, it did display timestamps, but updating the lists of episodes will fail silently.

**Comment by nullobsi** [comment]
This was a bug introduced in f85d76e9a2a2409b2737d59e0685ea8d1ea4fed3. Thanks for pointing it out.
