### ISSUE TITLE
bug: Can't find downloaded podcasts

### ISSUE THREAD

**Issue by talmage** [nullobsi/cantata#39]
**System Details**
OS: Pop! OS 22.04 LTS
Arch: x86_64
Desktop Environment: KDE
Version: v3.2.1
Installed by: Flatpak

**Describe the bug**
Cantata appears to download podcast episodes.  When the download finishes, the file isn't on the filesystem.

**To Reproduce**
1. Go to Internet
2. Click on a podcast series
3. Select an episode
4. Right click, then select Download Episodes.
5. Look for the downloaded file.

**Expected behavior**
I expect the downloaded file to be in the directory Music/Podcasts/Foo, where Foo is the name of the podcast.

**Screenshots**

**Additional context**
Version 2.4.2, which I installed using `apt`, doesn't exhibit this problem.  It puts downloaded podcast episodes in the right place.

**Comment by nullobsi** [comment]
It looks like Cantata defaults to saving podcasts under ~/Podcasts and not ~/Music/Podcasts. This is an issue because the Flatpak does not have access to the full home directory.
