### ISSUE TITLE
Install from Arch Aur?

### ISSUE THREAD

**Issue by coffseducation** [nullobsi/cantata#4]
Hello again!
I was informed that you package is in the AUR!
I cannot get it to install however.

These methods donot work:

in repo: cantata-qt6 on  master took 61ms
╰─λ paru Ui
error: Too many package results.

Nor this below, noting that I had cmake installed then also tried cmake-git.

n repo: cantata-qt6 on  master [?] as :mage: took 13s
[:red_circle:] × makepkg
==> Making package: cantata-qt6 3.0.2-1 (Sun 26 May 2024 10:40:33)
==> Checking runtime dependencies…
==> Checking buildtime dependencies…
==> Retrieving sources…
→ Updating cantata-nullobsi git repo…
==> Validating source files with sha256sums…
cantata-nullobsi … Skipped
==> Extracting sources…
→ Creating working copy of cantata-nullobsi git repo…
Reset branch ‘makepkg’
==> Removing existing $pkgdir/ directory…
==> Starting build()…
Traceback (most recent call last):
File “/home/anarcho/.local/bin/cmake”, line 5, in
from cmake import cmake
ModuleNotFoundError: No module named ‘cmake’
==> ERROR: A failure occurred in build().
Aborting…

**Comment by nullobsi** [comment]
from what i see you might have some strange wrapper script in your ~/.local/bin that isn't working correctly?

**Comment by coffseducation** [comment]
huh? Ok.

In bin I have a cmake file with the following:

#!/home/anarcho/.local/pipx/venvs/suno-bark/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from cmake import cmake
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cmake())


Could this be the issue?

**Comment by nullobsi** [comment]
seems like it, i really have no clue what that might be and it conflicts with `cmake`, try removing it and see if that lets you build it

**Comment by coffseducation** [comment]
I deleted that file and Cantata built!
Yay!

How do I launch it???

**Comment by coffseducation** [comment]
Would your flatpak version of Cantata mess with the launch?
I have it installed also.

**Comment by coffseducation** [comment]
SOLVED!
/home/anarcho/.cache/paru/clone/cantata-qt6-git/pkg/cantata-qt6-git/usr/bin/cantata

Looks great!
Thanks for your effort with this!
Legend! 🙏

**Comment by nullobsi** [comment]
make sure you install the built package (should have done it if you did `makepkg -si`), and then you can remove the flatpak since you're doing a system install now. Then you can run `cantata` from the command line or use the application entry.

** use `sudo pacman -U /path/to/cantata.pkg.zst` to install
