### ISSUE TITLE
Icon does not change when using another desktop theme

### ISSUE THREAD

**Issue by gsanhueza** [nullobsi/cantata#5]
Hello! It's nice to see this project ported to Qt6, and I'm thankful for your efforts!

When using the original project, it was possible to change Cantata's icon by changing the desktop theme (like Breeze or Oxygen in KDE, to another icon theme).
But now the icon seems to be named "dog.unix.cantata.Cantata" instead of "cantata", so icon themes cannot override the original one anymore, and the icon does not change as one would expect.

Would it be possible to restore the icon's name, so it's possible to use custom themes as before?

**Comment by nullobsi** [comment]
So this is a new requirement for Flatpak builds and there are currently no plans to change it back.  If you'd like, you can probably use .local/share/icons and rename them yourself, but icon packs might have to be updated.

**Comment by gsanhueza** [comment]
Now I understand the reasoning for the name change (a Flatpak requirement).

And the workaround that you proposed restores the expected behavior, so now we wait whether all icon themes update the naming, or another fork with the original name is used.

Thanks for your response!
