### ISSUE TITLE
Radio Favourites

### ISSUE THREAD

**Issue by coffseducation** [nullobsi/cantata#6]
Hearting a radio station does not work.
It does not get added to Favourites.

nb. Manually adding stations to the [Radio Streams].m3u works.

**Comment by nullobsi** [comment]
It appears to be working for me. Could it be permissions issues with the MPD server?

**Comment by coffseducation** [comment]
RESOLVED:

I am not too sure how. I ended up bak-ing the mpd directory in /home/user/.local/share/Cantata/mpd
so it recreated. It did not work. Ugh! So, I just replaced my m3u list anyway.
I tried once more and bingo! It is now adding to favourites!

**Comment by coffseducation** [comment]
And broken again! 😂

**Comment by coffseducation** [comment]
Ok, it seems to be a fault of search.
i.e If I manually navigate through the file directory I can choose a station and add to favourites. ✅
If I use the search function and try to add a station it fails. ❌

**Comment by nullobsi** [comment]
thanks for the info, i was able to reproduce

**Comment by nullobsi** [comment]
it's honestly a really strange issue and will need a bit of digging. using the debugger hasn't helped lol
